version: '2'
services:
  webapp:
    build: ./data-svc
    ports:
      - "9001:9001"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  pather:
      build: ./pather
      ports:
        - "9003:9003"
      logging:
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"
