server:
  port: 9001
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://data-svc-db:5432/postgres #jdbc:h2:mem:mydb #
    password: postgres
    username: postgres