server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    #url: jdbc:h2:mem:mydb
    password: postgres
    username: postgres

