platform :ios, '9.0'

target 'RamblinTreks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RamblinTreks

    pod 'GoogleMaps'
    pod 'TextFieldEffects'
    pod 'SideMenu'
    pod 'SwiftyJSON'
    pod 'Alamofire'

end
